/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uva.ipc.loginmultilpesvistas.vista;

/**
 *
 * @author macoa
 */
public class VistaLogin extends javax.swing.JFrame {
    
    private ControladorLogin controlador;

    /**
     * Creates new form VistaLogin
     */
    public VistaLogin() {
        initComponents();
        controlador=new ControladorLogin(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        accederButton = new javax.swing.JButton();
        cambiarDatosButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        usuarioTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        mensajeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(200, 100));
        setPreferredSize(new java.awt.Dimension(400, 200));

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        accederButton.setText("Acceder");
        accederButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accederButtonActionPerformed(evt);
            }
        });
        jPanel4.add(accederButton);

        cambiarDatosButton.setText("Cambiar Datos");
        cambiarDatosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarDatosButtonActionPerformed(evt);
            }
        });
        jPanel4.add(cambiarDatosButton);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Usuario: ");
        jLabel2.setAlignmentY(0.0F);
        jPanel5.add(jLabel2);

        usuarioTextField.setColumns(10);
        usuarioTextField.setAlignmentX(0.0F);
        usuarioTextField.setAlignmentY(0.0F);
        jPanel5.add(usuarioTextField);

        jLabel1.setText("Contraseña: ");
        jPanel5.add(jLabel1);

        passwordTextField.setColumns(10);
        jPanel5.add(passwordTextField);

        jPanel2.add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel1.add(mensajeLabel);

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accederButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accederButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesaEventoAcceder();
    }//GEN-LAST:event_accederButtonActionPerformed

    private void cambiarDatosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarDatosButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesaEventoCambiarDatos();
    }//GEN-LAST:event_cambiarDatosButtonActionPerformed

    public String getUsuario(){
        return usuarioTextField.getText();
    }
    
    public String getPassword(){
        return passwordTextField.getText();
    }
   
    public void mostrarMensaje(String mensaje){
        mensajeLabel.setText(mensaje);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accederButton;
    private javax.swing.JButton cambiarDatosButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel mensajeLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JTextField usuarioTextField;
    // End of variables declaration//GEN-END:variables
}
