/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uva.ipc.loginmultilpesvistas.vista;

/**
 *
 * @author macoa
 */
public class VistaCambiarDatos extends javax.swing.JFrame {
    
    private ControladorCambiarDatos controlador;

    /**
     * Creates new form VistaLogin
     */
    public VistaCambiarDatos() {
        initComponents();
        controlador=new ControladorCambiarDatos(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        guardarButton = new javax.swing.JButton();
        volverALoginButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        usuarioTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        repetirPassTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        mensajeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cambiar Datos");
        setPreferredSize(new java.awt.Dimension(700, 200));

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });
        jPanel4.add(guardarButton);

        volverALoginButton.setText("Volver a login");
        volverALoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverALoginButtonActionPerformed(evt);
            }
        });
        jPanel4.add(volverALoginButton);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Usuario: ");
        jLabel2.setAlignmentY(0.0F);
        jPanel5.add(jLabel2);

        usuarioTextField.setColumns(10);
        usuarioTextField.setAlignmentX(0.0F);
        usuarioTextField.setAlignmentY(0.0F);
        jPanel5.add(usuarioTextField);

        jLabel1.setText("Contraseña: ");
        jPanel5.add(jLabel1);

        passwordTextField.setColumns(10);
        jPanel5.add(passwordTextField);

        jLabel3.setText("Repetir contraseña: ");
        jPanel5.add(jLabel3);

        repetirPassTextField.setColumns(10);
        jPanel5.add(repetirPassTextField);

        jPanel2.add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel1.add(mensajeLabel);

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesaEventoGuardar();
    }//GEN-LAST:event_guardarButtonActionPerformed

    private void volverALoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverALoginButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesaEventoVolverALogin();
    }//GEN-LAST:event_volverALoginButtonActionPerformed

    public String getUsuario(){
        return usuarioTextField.getText();
    }
    
    public String getPassword(){
        return passwordTextField.getText();
    }
    
    public String getPasswordRepetida(){
        return repetirPassTextField.getText();
    }
   
    public void mostrarMensaje(String mensaje){
        mensajeLabel.setText(mensaje);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guardarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel mensajeLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JTextField repetirPassTextField;
    private javax.swing.JTextField usuarioTextField;
    private javax.swing.JButton volverALoginButton;
    // End of variables declaration//GEN-END:variables
}
