/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uva.ipc.loginmultilpesvistas.vista;

/**
 *
 * @author macoa
 */
public class VistaSeccionRestringida extends javax.swing.JFrame {
    
    private ControladorSeccionRestringida controlador;

    /**
     * Creates new form VistaRestringida
     */
    public VistaSeccionRestringida() {
        initComponents();
        controlador=new ControladorSeccionRestringida(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreUsuarioLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cerrarSesionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sección Usuario");
        setPreferredSize(new java.awt.Dimension(400, 200));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel1.add(nombreUsuarioLabel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        cerrarSesionButton.setText("Cerrar Sesión");
        cerrarSesionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cerrarSesionButton);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSesionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionButtonActionPerformed
        // TODO add your handling code here:
        controlador.procesaEventoCerrarSesion();
    }//GEN-LAST:event_cerrarSesionButtonActionPerformed

    public void mostrarNombreUsuario(String nombreUsuario){
        this.nombreUsuarioLabel.setText(nombreUsuario);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarSesionButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nombreUsuarioLabel;
    // End of variables declaration//GEN-END:variables
}
